
  - name: Install zip
    become: yes
    apt:
      name: zip
      state: latest
      update_cache: yes

  - name: Install htop
    become: yes
    apt:
      name: htop
      state: latest
      update_cache: yes

